version: '2'

volumes:
  craftcms-data:
  postgresql-data:
  redis-data:
  craftcms-logs:

services:
  www:
    build: .
    restart: unless-stopped
  dev-live:
    build: ./dockerfiles/live
    restart: unless-stopped
  web:
    image: wyveo/craftcms-docker:latest
    restart: unless-stopped
    ports:
      - 8005:80
    volumes:
      - craftcms-logs:/var/log
      - craftcms-data:/usr/share/nginx
    links:
      - postgres
      - redis
    # env vars are replaced in .env
    environment:
      # Set locale to UTF-8 (https://oncletom.io/2015/docker-encoding/)
      LANG: C.UTF-8

      # REDIS is linked
      REDIS_HOST: redis
      REDIS_PORT_6379_TCP: tcp://redis:6379

      # DB is linked
      DB_DRIVER: pgsql
      DB_SERVER: postgres
      DB_DATABASE: craft3
      DB_PASSWORD: nKR9K2ECuVAEM9tqYsMtDpXa
      PGPASSWORD: nKR9K2ECuVAEM9tqYsMtDpXa
      DB_SCHEMA: public
      DB_PORT: '5432'
      DB_USER: craft3

      ASSET_BASE_URL: ''
      ASSET_FS_PATH: ''

  postgres:
    image: postgres:11.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: craft3
      POSTGRES_PASSWORD: nKR9K2ECuVAEM9tqYsMtDpXa
      POSTGRES_DB: craft3
      POSTGRES_INITDB_ARGS: "-E UTF8"
    volumes:
      # Persistent data
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.6-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
