name: Publish Website

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
        env: # Or as an environment variable
          API_AUTH: ${{ secrets.API_AUTH }}
      # Use rsync to upload website to another server
      # ! Disable uploading websites
      # - name: Upload website
      #   shell: bash
      #   run: |
      #     mkdir -p ~/.ssh && chmod 700 ~/.ssh
      #     echo "${{ secrets.PRIVATE_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     rm -rf ./public/.git # Remove unused folder
      #     rsync -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" -havr --delete ./public/ root@47.56.199.173:/root/works/docker_static_nginx/sample_web_app
